### ISSUE TITLE
Trouble installing via conda

### ISSUE THREAD

**Issue by johncwok** [krischer/mtspec#34]
When trying to install the package via conda, i get the following error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - mtspec

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
```
pip install didn't work as well so I currently have no way of installing the pacakge. Do you know a workaround ?

**Comment by krischer** [comment]
Hi @johncwok 

we currently don't build conda packages for windows because it did not work as expected a few years ago. See here for one of our old tries: https://github.com/conda-forge/mtspec-feedstock/pull/5

Maybe this is easier today and it would just work. I'd be happy to accept any pull requests regarding that.

Also pinging @ThomasLecocq because I know he installed `mtspec` on windows.

Another option would be to install WSL and the mtspec `conda` package should work just fine there.

**Comment by ThomasLecocq** [comment]
myaeah... I did indeed, but compiled from source, and there are stuff that didn't really work, but that could very well be in all versions (parameters/type of mt didn't pass to the c code)

**Comment by johncwok** [comment]
Then I will just use R. Using Python was mostly to be able to do pretty plots but since I just want to visualize my the results I don't think it is worth investing too much effort into it.
Thanks for your quick reply though !

**Comment by ThomasLecocq** [comment]
wooops @krischer
